# Generated by Django 3.1.4 on 2020-12-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmy',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmy'},
        ),
    ]
