# Generated by Django 3.1.4 on 2020-12-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_auto_20201228_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmy',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
