# Generated by Django 3.1.4 on 2020-12-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0006_auto_20201229_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
