# Generated by Django 3.1.4 on 2020-12-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0007_auto_20201229_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
