# Generated by Django 3.1.4 on 2021-01-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0008_auto_20201229_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filmy',
            new_name='movie',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
    ]
