# Generated by Django 3.1.4 on 2021-01-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0009_auto_20210101_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ticketAvailability',
            field=models.BooleanField(default=True),
        ),
    ]
